#!/usr/bin/env python3
"""Flag destructive or locking operations in a freshly generated migration.

QuoinAPI follows an expand/contract discipline for zero-downtime schema
changes (see ``docs/guides/database-migrations.md``). Autogenerated Alembic
scripts happily emit destructive operations - ``drop_column``, type changes,
non-concurrent index builds - that are unsafe to apply against a live,
populated database while the old application version is still running.

This guard runs automatically after ``just migrate-gen``. It parses the newest
script in ``alembic/versions/`` and prints advisory review flags for any
operation that needs an expand/contract treatment or a maintenance window.
It is intentionally **non-blocking**: it always exits ``0`` so it never
stops the workflow. The flags are a prompt to review, not a verdict.

The scan walks the migration's AST so multi-line ``op.*`` calls (the shape
Alembic autogenerate emits) are matched as whole statements, not line by
line.

Usage:
    python scripts/migration_guard.py [path/to/migration.py]

With no argument, the most recently modified file under
``alembic/versions/`` is scanned.
"""

import ast
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

VERSIONS_DIR = Path("alembic/versions")
PLAYBOOK = "docs/guides/database-migrations.md"

# ``nullable=False`` but not Alembic's ``existing_nullable=False`` (which it
# emits as context on a type change and must not trip the NOT NULL rule).
_NOT_NULL = re.compile(r"\bnullable\s*=\s*False")

# Match destructive SQL by its statement-leading keywords (DELETE FROM,
# TRUNCATE, DROP <object>) rather than the bare words, so the keywords
# appearing inside string data (e.g. 'Drop-off point', 'do not delete') do
# not raise false positives.
_DESTRUCTIVE_SQL = re.compile(
    r"\bDELETE\s+FROM\b"
    r"|\bTRUNCATE\b"
    r"|\bDROP\s+(?:TABLE|INDEX|COLUMN|CONSTRAINT|SCHEMA|TYPE|VIEW|SEQUENCE)\b",
    re.IGNORECASE,
)

# An explicit ``server_default=None`` provides no real default, so it must
# not satisfy the add-column NOT NULL escape hatch.
_SERVER_DEFAULT_NONE = re.compile(r"server_default\s*=\s*None")


@dataclass(frozen=True)
class Flag:
    """A single flagged operation found in a migration script.

    Attributes:
        line: 1-based line number where the operation begins.
        text: The first line of the flagged ``op.*`` call.
        reason: Why the operation needs review.
        guidance: The expand/contract remedy to consider.
    """

    line: int
    text: str
    reason: str
    guidance: str


def _newest_migration() -> Path | None:
    """Return the most recently modified migration script, if any."""
    if not VERSIONS_DIR.is_dir():
        return None
    scripts = [p for p in VERSIONS_DIR.glob("*.py") if p.name != "__init__.py"]
    if not scripts:
        return None
    return max(scripts, key=lambda p: p.stat().st_mtime)


def _batch_receivers(tree: ast.Module) -> set[str]:
    """Return names bound by ``op.batch_alter_table(...) as <name>`` blocks.

    Alembic can wrap destructive operations in a batch context
    (``with op.batch_alter_table("t") as batch_op: batch_op.drop_column(...)``).
    The operation is then a method on the bound name rather than on ``op``,
    so those names must be treated as operation receivers too.

    Args:
        tree: The parsed migration module.

    Returns:
        The set of variable names bound by ``batch_alter_table`` ``with``
        items (conventionally ``{"batch_op"}``, but any name is honored).
    """
    names: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.With):
            continue
        for item in node.items:
            call = item.context_expr
            if (
                isinstance(call, ast.Call)
                and isinstance(call.func, ast.Attribute)
                and call.func.attr == "batch_alter_table"
                and isinstance(item.optional_vars, ast.Name)
            ):
                names.add(item.optional_vars.id)
    return names


def _op_method(node: ast.Call, receivers: set[str]) -> str | None:
    """Return the method name of a ``<receiver>.<method>(...)`` call.

    Args:
        node: The call node under inspection.
        receivers: Names that count as operation receivers (``"op"`` plus
            any batch-context names from :func:`_batch_receivers`).

    Returns:
        The method name when ``node`` is a call on one of ``receivers``,
        otherwise ``None``.
    """
    func = node.func
    if (
        isinstance(func, ast.Attribute)
        and isinstance(func.value, ast.Name)
        and func.value.id in receivers
    ):
        return func.attr
    return None


def _has_server_default(src: str) -> bool:
    """Return True if the call source declares a real ``server_default``.

    An explicit ``server_default=None`` is treated as *no* default, since it
    supplies no database-side value to backfill a NOT NULL column.

    Args:
        src: The full source text of the ``add_column`` call.

    Returns:
        Whether a non-``None`` ``server_default`` is present.
    """
    return "server_default" in src and not _SERVER_DEFAULT_NONE.search(src)


@dataclass(frozen=True)
class _Rule:
    """A single detection rule applied to one ``op.<method>`` call.

    Attributes:
        matches: Predicate over ``(method, source)`` for the call.
        reason: Why the matched operation needs review.
        guidance: The expand/contract remedy to consider.
    """

    matches: Callable[[str, str], bool]
    reason: str
    guidance: str


# Ordered: the first matching rule wins, so the more specific ``alter_column``
# type-change rule precedes the NOT-NULL one. ``src`` is the full (possibly
# multi-line) source segment of the call.
_RULES: list[_Rule] = [
    _Rule(
        lambda m, s: m == "drop_column",
        "drops a column - irreversible data loss",
        "Contract phase: ship the code that stops reading/writing this "
        "column FIRST, deploy, then drop in a later migration.",
    ),
    _Rule(
        lambda m, s: m == "drop_table",
        "drops a table - irreversible data loss",
        "Contract phase: retire all readers/writers first, then drop in a "
        "follow-up release.",
    ),
    _Rule(
        lambda m, s: m == "drop_constraint",
        "drops a constraint - may break invariants the running app relies on",
        "Confirm no in-flight code depends on this constraint before applying.",
    ),
    _Rule(
        lambda m, s: m == "execute" and bool(_DESTRUCTIVE_SQL.search(s)),
        "raw SQL performs a destructive operation (DROP/DELETE/TRUNCATE)",
        "Treat as a contract-phase change; review against the playbook "
        "before applying to production data.",
    ),
    _Rule(
        lambda m, s: m == "alter_column" and "type_=" in s,
        "changes a column type - may rewrite the table under an exclusive "
        "lock and can lose data on narrowing",
        "Expand/contract: add a new column, dual-write + backfill, switch "
        "reads, then drop the old column.",
    ),
    _Rule(
        lambda m, s: m == "alter_column" and bool(_NOT_NULL.search(s)),
        "sets NOT NULL on an existing column - scans/locks the table and "
        "fails if any row is NULL",
        "Backfill first, then add a CHECK ... NOT VALID + VALIDATE, or set "
        "NOT NULL in a low-traffic window.",
    ),
    _Rule(
        lambda m, s: (
            m == "add_column"
            and bool(_NOT_NULL.search(s))
            and not _has_server_default(s)
        ),
        "adds a NOT NULL column without a server_default - fails on a "
        "populated table",
        "Add the column nullable (or with a server_default), backfill, then "
        "tighten to NOT NULL in a later step.",
    ),
    _Rule(
        lambda m, s: (
            m == "create_index" and "postgresql_concurrently=True" not in s
        ),
        "creates an index without CONCURRENTLY - locks the table against "
        "writes on Postgres",
        "Pass postgresql_concurrently=True (and run outside a transaction) "
        "for large tables.",
    ),
    _Rule(
        lambda m, s: (
            m == "drop_index" and "postgresql_concurrently=True" not in s
        ),
        "drops an index without CONCURRENTLY - takes a brief exclusive lock",
        "Pass postgresql_concurrently=True for hot tables.",
    ),
]


def _classify(method: str, src: str) -> tuple[str, str] | None:
    """Classify an ``op.<method>`` call by its source segment.

    Args:
        method: The ``op`` method name (e.g. ``"drop_column"``).
        src: The full source text of the call (may span lines).

    Returns:
        A ``(reason, guidance)`` pair from the first matching rule, else
        ``None``.
    """
    for rule in _RULES:
        if rule.matches(method, src):
            return rule.reason, rule.guidance
    return None


def scan(text: str) -> list[Flag]:
    """Scan migration source text and return all flagged operations.

    Args:
        text: The full source of a migration script.

    Returns:
        A list of ``Flag`` objects, one per risky call, in file order.
        Returns an empty list if the source cannot be parsed.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError, ValueError:
        return []

    receivers = {"op"} | _batch_receivers(tree)
    flags: list[Flag] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        method = _op_method(node, receivers)
        if method is None:
            continue
        src = ast.get_source_segment(text, node) or ""
        verdict = _classify(method, src)
        if verdict is None:
            continue
        reason, guidance = verdict
        first_line = src.splitlines()[0].strip() if src else f"op.{method}(...)"
        flags.append(Flag(node.lineno, first_line, reason, guidance))

    flags.sort(key=lambda f: f.line)
    return flags


def _report(path: Path, flags: list[Flag]) -> None:
    """Print the guard report for a scanned migration."""
    if not flags:
        print(f"[migration-guard] {path.name}: no unsafe operations detected.")
        return

    print("")
    print("=" * 72)
    print(f"[migration-guard] {len(flags)} operation(s) flagged for review")
    print(f"  file: {path}")
    print(f"  playbook: {PLAYBOOK} (zero-downtime / expand-contract)")
    print("=" * 72)
    for f in flags:
        print(f"\n  L{f.line}: {f.text}")
        print(f"    why:  {f.reason}")
        print(f"    fix:  {f.guidance}")
    print("")
    print(
        "These are advisory. If you intend the change and have a "
        "maintenance\nwindow (or the table is small), proceed. Otherwise "
        "split it into an\nexpand/contract sequence per the playbook."
    )
    print("")


def main(argv: list[str]) -> int:
    """Entry point. Returns 0 always (advisory, never blocking)."""
    # Defense in depth: under a non-UTF-8 stdout locale (e.g. LANG=C in a
    # minimal CI/Docker image) printing any non-ASCII character would raise
    # UnicodeEncodeError, and because the guard is chained after `alembic
    # revision` in `just migrate-gen`, that crash would abort the recipe.
    # Replace unencodable characters instead of raising.
    reconfigure = getattr(sys.stdout, "reconfigure", None)
    if callable(reconfigure):
        reconfigure(errors="backslashreplace")

    if len(argv) > 1:
        path = Path(argv[1])
        if not path.is_file():
            print(f"[migration-guard] not a file: {path}")
            return 0
    else:
        found = _newest_migration()
        if found is None:
            print("[migration-guard] no migration scripts to scan.")
            return 0
        path = found

    flags = scan(path.read_text())
    _report(path, flags)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
